### ISSUE TITLE
Fractions : Où trouver le caractère 1/2

### ISSUE THREAD

**Issue by gjobin** [ergosteur/cf-keylayout#12]
Salut,

Merci pour le beau travail !
Normalement, alt+0, alt+ - et alt + +, font respectivement les fractions 1/4, 1/2 et 3/4

Par contre, j'obtiens le résulat suivant : ¼–¾
Comment produire le caractère 1/2 ?

Merci,
Guillaume

**Comment by ferd** [comment]
`<option> + -` = ½

**Comment by joallard** [comment]
En effet, `alt + -` donne `–`, un en-dash. À mon avis le symbole (1/2) est moins utile que les tirets, mais c'est discutable. Je ne saurais pas où mettre le 1/2 sans enlever cette fonctionnalité-là. 

À la limite, rien ne nous empêche de taper ½ avec le clavier Unicode Hex Input en faisant `Alt + 00bd`, un peu comme d'autres signes spéciaux comme `ñ` habituellement. (mais on l'a)

**Comment by jrobichaud** [comment]
Pour changer `–` pour  `½` il faut remplacer:
```xml
<key code="27" output="&#x2013;" />
```
 par:
```xml
<key code="27" output="&#xbd;" />
```

Cependant pour éviter d'écraser une autre touche je suggèrerais  `Alt+Shift+0` pour être `½`.  `Alt+ 0` c'est `¼` alors ça garde une certaine logique.

Pour faire ça dans la section:
```xml
<keyMap index="4">
```
Ajouter:
```xml
<key code="29" output="&#xbd;" />
```

Qu'en pensez-vous?

**Comment by gjobin** [comment]
Je pense qu'il y aurait au moins un façon de le faire.

**Comment by joallard** [comment]
@jrobichaud J'aime ça

**Comment by jrobichaud** [comment]
J'ai fait la PR #13 si vous voulez l'ajouter à Alt+Shift+0.

**Comment by joallard** [comment]
Très clean, merci @jrobichaud. C'est dans master, je vais penser à incrémenter la version sous peu.

**Comment by gjobin** [comment]
Merci les gars pour votre support! C'est très apprécié.
