### ISSUE TITLE
Alt+{key} not working when on CapsLock

### ISSUE THREAD

**Issue by gjobin** [ergosteur/cf-keylayout#15]
Les raccourcis pour les caractères alternatifs ne fonctionnent pas lorsque CapsLock est activé.
Donc ces caractères ne fonctionnent pas en CapsLock : ~{}[]\±@£¢¤¬¦²³¼–¾

**Comment by jrobichaud** [comment]
Je peux m’occuper de fixer ça.

**Comment by gjobin** [comment]
Un grand merci!

**Comment by jrobichaud** [comment]
C'est fait.

**Comment by gjobin** [comment]
J'ai fait un pull de ta branche et installé. Fix confirmé !  Merci.

**Comment by joallard** [comment]
1998 ont appelé, ils reveulent leur touche CapsLock
