### ISSUE TITLE
High Sierra - Impossible to select this layout in Mail

### ISSUE THREAD

**Issue by TP-Crypto** [ergosteur/cf-keylayout#17]
I just upgraded to High Sierra (i know, it's time...). In few applications (like Mail, Telegram...), the "ABC - Étendu" layout is automatically selected. I'm trying to select the "Canadien français 0.12.1" and it doesn't accept it. However, I can select it in Chrome. Any idea why? Thank you for your support.

**Comment by joallard** [comment]
Okay, thanks for your report

**Comment by joallard** [comment]
Resolution: Moving the layout to `$HOME/Library/Keyboard Layouts/`
