### ISSUE TITLE
Alt + - should be ½

### ISSUE THREAD

**Issue by jul059** [ergosteur/cf-keylayout#19]
The combination of Alt + - should be ½, not – (which it currently is). For example, see http://www3.uakron.edu/modlang/french/keyboard.html or http://ascii-table.com/keyboard.php/058

I have never seen a French Canadian keyboard without the ½ in that position.

**Comment by jrobichaud** [comment]
See: https://github.com/ergosteur/cf-keylayout/issues/12

**Comment by joallard** [comment]
Yup, it's available as Alt+Shift+0

**Comment by ergosteur** [comment]
I've moved the en/em dash to Alt+, and Alt+Shift+, respectively - and switched Alt+- to ½.
Hope this can be a compromise between offering the en/em dash and being consistent with the key labels on physical French Canadian keyboards.
